/**
 * @fileoverview ExecutionKernel interface definition
 * @description Defines the core execution engine interface of Record-Replay V3
 */

import type { JsonObject } from '../../domain/json';
import type { FlowId, NodeId, RunId } from '../../domain/ids';
import type { RRError } from '../../domain/errors';
import type { FlowV3 } from '../../domain/flow';
import type { DebuggerCommand, DebuggerState } from '../../domain/debug';
import type { RunEvent, RunStatus, Unsubscribe } from '../../domain/events';

/**
 * Run start request
 */
export interface RunStartRequest {
  /** Run ID (generated by the caller) */
  runId: RunId;
  /** Flow ID */
  flowId: FlowId;
  /** Flow snapshot (full Flow definition used during execution) */
  flowSnapshot: FlowV3;
  /** Run args */
  args?: JsonObject;
  /** Start node ID (defaults to the Flow's entryNodeId) */
  startNodeId?: NodeId;
  /** Tab ID (must be allocated by the caller, exclusive per Run) */
  tabId: number;
  /** Debug config */
  debug?: { breakpoints?: NodeId[]; pauseOnStart?: boolean };
}

/**
 * Run execution result
 */
export interface RunResult {
  /** Run ID */
  runId: RunId;
  /** Final status */
  status: Extract<RunStatus, 'succeeded' | 'failed' | 'canceled'>;
  /** Total duration (milliseconds) */
  tookMs: number;
  /** Error info (if failed) */
  error?: RRError;
  /** Output results */
  outputs?: JsonObject;
}

/**
 * Run status query result
 */
export interface RunStatusInfo {
  /** Current status */
  status: RunStatus;
  /** Current node ID */
  currentNodeId?: NodeId;
  /** Start time */
  startedAt?: number;
  /** Last update time */
  updatedAt: number;
  /** Tab ID */
  tabId?: number;
}

/**
 * ExecutionKernel interface
 * @description Core execution engine of Record-Replay V3
 */
export interface ExecutionKernel {
  /**
   * Subscribe to the event stream
   * @param listener Event listener
   * @returns Unsubscribe function
   */
  onEvent(listener: (event: RunEvent) => void): Unsubscribe;

  /**
   * Start a Run
   * @description Enqueues the Run and starts execution
   */
  startRun(req: RunStartRequest): Promise<void>;

  /**
   * Pause a Run
   * @param runId Run ID
   * @param reason Pause reason
   */
  pauseRun(runId: RunId, reason?: { kind: 'command' }): Promise<void>;

  /**
   * Resume a Run
   * @param runId Run ID
   */
  resumeRun(runId: RunId): Promise<void>;

  /**
   * Cancel a Run
   * @param runId Run ID
   * @param reason Cancel reason
   */
  cancelRun(runId: RunId, reason?: string): Promise<void>;

  /**
   * Execute a debugger command
   * @param runId Run ID
   * @param cmd Debugger command
   */
  debug(
    runId: RunId,
    cmd: DebuggerCommand,
  ): Promise<{ ok: true; state?: DebuggerState } | { ok: false; error: string }>;

  /**
   * Get the Run status
   * @param runId Run ID
   * @returns Run status info or null (if not found)
   */
  getRunStatus(runId: RunId): Promise<RunStatusInfo | null>;

  /**
   * Recover execution
   * @description Called after a Service Worker restart to recover interrupted Runs
   */
  recover(): Promise<void>;
}

/**
 * Create a NotImplemented ExecutionKernel
 * @description Phase 0 placeholder implementation
 */
export function createNotImplementedKernel(): ExecutionKernel {
  const notImplemented = () => {
    throw new Error('ExecutionKernel not implemented');
  };

  return {
    onEvent: () => {
      notImplemented();
      return () => {};
    },
    startRun: async () => notImplemented(),
    pauseRun: async () => notImplemented(),
    resumeRun: async () => notImplemented(),
    cancelRun: async () => notImplemented(),
    debug: async () => notImplemented(),
    getRunStatus: async () => notImplemented(),
    recover: async () => notImplemented(),
  };
}
